[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2025.2.0-19140-c01cd93e24d-releases/2025/2
[ INFO ] 
[ INFO ] Device info:
[ INFO ] NPU
[ INFO ] Build ................................. 2025.2.0-19140-c01cd93e24d-releases/2025/2
[ INFO ] 
[ INFO ] 
[Step 3/11] Setting device configuration
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 9.48 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Model inputs:
[ INFO ]     x (node: x) : f32 / [...] / [2708,1433]
[ INFO ]     edge_index (node: edge_index) : i64 / [...] / [2,10556]
[ INFO ] Model outputs:
[ INFO ]     z.1 (node: aten::linear/Add_1) : f32 / [...] / [2708,7]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Model batch size: 1
[Step 6/11] Configuring input of the model
[ INFO ] Model inputs:
[ INFO ]     x (node: x) : f16 / [...] / [2708,1433]
[ INFO ]     edge_index (node: edge_index) : f16 / [...] / [2,10556]
[ INFO ] Model outputs:
[ INFO ]     z.1 (node: aten::linear/Add_1.0) : f16 / [...] / [2708,7]
[Step 7/11] Loading the model to the device
[ ERROR ] Exception from src\inference\src\cpp\core.cpp:112:
Exception from src\inference\src\dev\plugin.cpp:53:
Exception from src\plugins\intel_npu\src\plugin\src\plugin.cpp:492:
Exception from src\plugins\intel_npu\src\compiler_adapter\src\ze_graph_ext_wrappers.cpp:314:
L0 pfnCreate2 result: ZE_RESULT_ERROR_INVALID_ARGUMENT, code 0x78000004 - generic error code for invalid arguments . 


Traceback (most recent call last):
  File "C:\Users\phamh\miniconda3\envs\gnn\Lib\site-packages\openvino\tools\benchmark\main.py", line 449, in main
    compiled_model = benchmark.core.compile_model(model, benchmark.device, device_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phamh\miniconda3\envs\gnn\Lib\site-packages\openvino\_ov_api.py", line 599, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception from src\inference\src\cpp\core.cpp:112:
Exception from src\inference\src\dev\plugin.cpp:53:
Exception from src\plugins\intel_npu\src\plugin\src\plugin.cpp:492:
Exception from src\plugins\intel_npu\src\compiler_adapter\src\ze_graph_ext_wrappers.cpp:314:
L0 pfnCreate2 result: ZE_RESULT_ERROR_INVALID_ARGUMENT, code 0x78000004 - generic error code for invalid arguments . 



